os: Visual Studio 2017
platform: x64

environment:
  MINICONDA_ROOT: C:\Miniconda36-x64
  GENERATOR: Visual Studio 15 2017 Win64
  CONFIG: Release
  BOOST_ROOT: C:\Libraries\boost_1_66_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_66_0\lib64-msvc-14.1
  PATH: "%BOOST_LIBRARYDIR%;%PATH%"

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  # Install SWIG
  - ps: choco install -y --no-progress --allow-empty-checksums -r swig --version 4.0.1
  - cmd: call %MINICONDA_ROOT%\Scripts\activate.bat
  # Install ZMQ
  - cmd: C:\Tools\vcpkg\vcpkg install zeromq:x64-windows

cache:
  - C:\Tools\vcpkg\installed
  - C:\Users\appveyor\AppData\Local\Temp\chocolatey

build_script:
  - md build
  - cd build
  - cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE="%CONFIG%" -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake ..
  - cmake --build . --config "%CONFIG%"
