dist: trusty
sudo: false

language: cpp

script:
- mkdir build
- cd build
- cmake ..
- make -j 2

addons:
  apt:
    packages:
    - libboost-dev
    - libboost-serialization-dev
    - libzmq3-dev
    - python3-dev
    - python3-zmq
    - swig

compiler:
- clang
#- gcc # too old :(
