dist: trusty
sudo: false

language: cpp

script:
- mkdir build
- cd build
- cmake ..
- make -j 2

addons:
  apt:
    update: true
    packages:
    - doxygen
    - libboost-dev
    - libboost-serialization-dev
    - libzmq3-dev
    - python3-dev
    - python3-zmq
    - swig

matrix:
  include:
  - compiler: clang
  # compiler: gcc
  - if: branch = master
    env: docs=yes
    script: bash doc/publish_documentation.sh
  allow_failures:
    - env: docs=yes
