CPP Patterns: /home/runner/work/cpp-patterns/cpp-patterns/argument-count/test.cpp File Reference
test.cpp File Reference
#include <iostream>
#include <cmath>
#include <type_traits>
Data Structures
struct argument_count< F >
struct argument_count< R(C::*)(Args...)>
struct argument_count< R(C::*)(Args...) const >
struct argument_count< R(Args...)>
struct argument_count< R(*)(Args...)>
struct A
struct B
Typedefs
template<unsigned v>
using unsigned_constant = std::integral_constant< unsigned, v >
Functions
void f (int, int, int)
int main ()
Typedef Documentation
unsigned_constant
template<unsigned v> using unsigned_constant = std::integral_constant<unsigned, v>
Definition at line 6 of file test.cpp.
Function Documentation
f()
void f (int , int , int)
Definition at line 24 of file test.cpp.
Referenced by cpp_function(), for_each(), for_each_impl(), main(), and unroll().
main()
int main ()
Definition at line 34 of file test.cpp.
References A::bar(), and f().