CPP Patterns: math::multi_array< T, N > Class Template Reference
math::multi_array< T, N > Class Template Reference
#include <multi_array.hpp>
Public Types
using value_type = T
using size_type = std::size_t
using difference_type = std::ptrdiff_t
using reference = value_type &
using const_reference = const value_type &
using pointer = value_type *
using const_pointer = const value_type *
using iterator = pointer
Public Member Functions
DEVICE_FUNC constexpr multi_array ()
template<typename... U>
DEVICE_FUNC constexpr multi_array (U...data)
Constructor for aggregate initializers.
DEVICE_FUNC void fill (value_type const &value) noexcept(std::is_nothrow_copy_assignable< value_type >::value)
fill the container with specified value
DEVICE_FUNC void swap (multi_array &other) noexcept(std::is_nothrow_move_assignable< value_type >::value)
swaps the contents
DEVICE_FUNC constexpr iterator begin () const noexcept
returns an iterator to the beginning
DEVICE_FUNC constexpr iterator end () const noexcept
returns an iterator to the end
DEVICE_FUNC CXX14_CONSTEXPR pointer data () noexcept
direct access to the underlying array
DEVICE_FUNC CXX14_CONSTEXPR
const_pointer data () const noexcept
template<typename... Idx>
DEVICE_FUNC CXX14_CONSTEXPR
reference operator() (Idx...idx)
template<typename... Idx>
DEVICE_FUNC constexpr
const_reference operator() (Idx...idx) const
template<size_type i>
DEVICE_FUNC constexpr size_type size () const noexcept
DEVICE_FUNC constexpr size_type size () const noexcept
returns the number of elements
Detailed Description
template<typename T, std::size_t... N>
class math::multi_array< T, N >
Multidimensional array similar to std::array
Storage is always in column-major order
Template Parameters
T value type
N list of dimensions
Definition at line 130 of file multi_array.hpp.
Member Typedef Documentation
template<typename T, std::size_t... N> using math::multi_array< T, N >::const_pointer = const value_type *
Definition at line 138 of file multi_array.hpp.
template<typename T, std::size_t... N> using math::multi_array< T, N >::const_reference = const value_type &
Definition at line 136 of file multi_array.hpp.
template<typename T, std::size_t... N> using math::multi_array< T, N >::difference_type = std::ptrdiff_t
Definition at line 134 of file multi_array.hpp.
template<typename T, std::size_t... N> using math::multi_array< T, N >::iterator = pointer
Definition at line 139 of file multi_array.hpp.
template<typename T, std::size_t... N> using math::multi_array< T, N >::pointer = value_type *
Definition at line 137 of file multi_array.hpp.
template<typename T, std::size_t... N> using math::multi_array< T, N >::reference = value_type &
Definition at line 135 of file multi_array.hpp.
template<typename T, std::size_t... N> using math::multi_array< T, N >::size_type = std::size_t
Definition at line 133 of file multi_array.hpp.
template<typename T, std::size_t... N> using math::multi_array< T, N >::value_type = T
Definition at line 132 of file multi_array.hpp.
Constructor & Destructor Documentation
template<typename T, std::size_t... N> DEVICE_FUNC constexpr math::multi_array< T, N >::multi_array () inline
Definition at line 152 of file multi_array.hpp.
template<typename T, std::size_t... N> template<typename... U> DEVICE_FUNC constexpr math::multi_array< T, N >::multi_array (U... data) inline
Constructor for aggregate initializers.
Definition at line 156 of file multi_array.hpp.
References math::multi_array< T, N >::data().
Member Function Documentation
template<typename T, std::size_t... N> DEVICE_FUNC constexpr iterator math::multi_array< T, N >::begin () const inline noexcept
returns an iterator to the beginning
Definition at line 178 of file multi_array.hpp.
References math::multi_array< T, N >::data().
Referenced by math::multi_array< T, N >::fill(), and math::multi_array< T, N >::swap().
template<typename T, std::size_t... N> DEVICE_FUNC CXX14_CONSTEXPR pointer math::multi_array< T, N >::data () inline noexcept
direct access to the underlying array
Definition at line 188 of file multi_array.hpp.
Referenced by math::multi_array< T, N >::begin(), math::multi_array< T, N >::end(), and math::multi_array< T, N >::multi_array().
template<typename T, std::size_t... N> DEVICE_FUNC CXX14_CONSTEXPR const_pointer math::multi_array< T, N >::data () const inline noexcept
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 190 of file multi_array.hpp.
template<typename T, std::size_t... N> DEVICE_FUNC constexpr iterator math::multi_array< T, N >::end () const inline noexcept
returns an iterator to the end
Definition at line 183 of file multi_array.hpp.
References math::multi_array< T, N >::data().
Referenced by math::multi_array< T, N >::fill(), and math::multi_array< T, N >::swap().
template<typename T, std::size_t... N> DEVICE_FUNC void math::multi_array< T, N >::fill (value_type const & value) inline noexcept
fill the container with specified value
Definition at line 159 of file multi_array.hpp.
References math::multi_array< T, N >::begin(), and math::multi_array< T, N >::end().
template<typename T, std::size_t... N> template<typename... Idx> DEVICE_FUNC CXX14_CONSTEXPR reference math::multi_array< T, N >::operator() (Idx... idx) inline
access specified element
Exceptions
std::out_of_range if index is out of range (only in DEBUG mode)
Definition at line 198 of file multi_array.hpp.
template<typename T, std::size_t... N> template<typename... Idx> DEVICE_FUNC constexpr const_reference math::multi_array< T, N >::operator() (Idx... idx) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 216 of file multi_array.hpp.
template<typename T, std::size_t... N> template<size_type i> DEVICE_FUNC constexpr size_type math::multi_array< T, N >::size () const inline noexcept
returns the size along dimension i
Template Parameters
i dimension
Definition at line 236 of file multi_array.hpp.
Referenced by main().
template<typename T, std::size_t... N> DEVICE_FUNC constexpr size_type math::multi_array< T, N >::size () const inline noexcept
returns the number of elements
Definition at line 242 of file multi_array.hpp.
template<typename T, std::size_t... N> DEVICE_FUNC void math::multi_array< T, N >::swap (multi_array< T, N > & other) inline noexcept
swaps the contents
Definition at line 167 of file multi_array.hpp.
References math::multi_array< T, N >::begin(), and math::multi_array< T, N >::end().
The documentation for this class was generated from the following file:
/home/travis/build/hmenke/cpp-patterns/multi_array/multi_array.hpp