CPP Patterns: math::device_matrix< T > Class Template Reference
math::device_matrix< T > Class Template Reference
Public Types
using value_type = typename storage_type::value_type
using size_type = typename storage_type::size_type
using difference_type = typename storage_type::difference_type
using reference = typename storage_type::reference
using const_reference = typename storage_type::const_reference
using pointer = typename storage_type::pointer
using const_pointer = typename storage_type::const_pointer
using iterator = typename storage_type::iterator
Public Member Functions
device_matrix (size_type rows, size_type cols)
reference operator() (size_type row, size_type col) noexcept
const_reference operator() (size_type row, size_type col) const noexcept
void fill (value_type const &value) noexcept(std::is_nothrow_copy_assignable< value_type >::value)
void swap (device_matrix &other) noexcept(noexcept(m_data.swap(other.m_data)))
pointer data () noexcept
const_pointer data () const noexcept
size_type rows () const noexcept
size_type cols () const noexcept
size_type size () const noexcept
device_matrix operator* (device_matrix const &B) const
Matrix-matrix multiplication.
device_matrix operator+ (device_matrix const &B) const
Add element-wise.
device_matrix operator- (device_matrix const &B) const
Subtract element-wise.
device_matrix & operator- ()
Negate element-wise.
bool operator== (device_matrix const &B) const
Compare for exact bit-wise equality.
bool almostEqual (device_matrix const &B, value_type const epsilon=std::numeric_limits< value_type >::epsilon()) const
device_matrix transpose () const
Compute the transpose.
device_matrix inverse () const
Compute the inverse.
Static Public Member Functions
static device_matrix Identity (size_type rows, size_type cols)
Generate an identity matrix with size rows x cols.
Detailed Description
template<typename T>
class math::device_matrix< T >
Definition at line 121 of file device_matrix.cuh.
Member Typedef Documentation
template<typename T> using math::device_matrix< T >::const_pointer = typename storage_type::const_pointer
Definition at line 132 of file device_matrix.cuh.
template<typename T> using math::device_matrix< T >::const_reference = typename storage_type::const_reference
Definition at line 130 of file device_matrix.cuh.
template<typename T> using math::device_matrix< T >::difference_type = typename storage_type::difference_type
Definition at line 128 of file device_matrix.cuh.
template<typename T> using math::device_matrix< T >::iterator = typename storage_type::iterator
Definition at line 133 of file device_matrix.cuh.
template<typename T> using math::device_matrix< T >::pointer = typename storage_type::pointer
Definition at line 131 of file device_matrix.cuh.
template<typename T> using math::device_matrix< T >::reference = typename storage_type::reference
Definition at line 129 of file device_matrix.cuh.
template<typename T> using math::device_matrix< T >::size_type = typename storage_type::size_type
Definition at line 127 of file device_matrix.cuh.
template<typename T> using math::device_matrix< T >::value_type = typename storage_type::value_type
Definition at line 126 of file device_matrix.cuh.
Constructor & Destructor Documentation
template<typename T> math::device_matrix< T >::device_matrix (size_type rows, size_type cols) inline explicit
Definition at line 142 of file device_matrix.cuh.
Member Function Documentation
template<typename T> size_type math::device_matrix< T >::cols () const inline noexcept
Definition at line 168 of file device_matrix.cuh.
template<typename T> pointer math::device_matrix< T >::data () inline noexcept
Definition at line 165 of file device_matrix.cuh.
Referenced by math::device_matrix< T >::almostEqual(), math::device_matrix< T >::Identity(), math::device_matrix< T >::inverse(), math::device_matrix< T >::operator*(), math::device_matrix< T >::operator+(), math::device_matrix< T >::operator-(), math::device_matrix< T >::operator==(), and math::device_matrix< T >::transpose().
template<typename T> const_pointer math::device_matrix< T >::data () const inline noexcept
Definition at line 166 of file device_matrix.cuh.
template<typename T> void math::device_matrix< T >::fill (value_type const & value) inline noexcept
Definition at line 153 of file device_matrix.cuh.
template<typename T> reference math::device_matrix< T >::operator() (size_type row, size_type col) inline noexcept
Definition at line 145 of file device_matrix.cuh.
template<typename T> const_reference math::device_matrix< T >::operator() (size_type row, size_type col) const inline noexcept
Definition at line 149 of file device_matrix.cuh.
template<typename T> size_type math::device_matrix< T >::rows () const inline noexcept
Definition at line 167 of file device_matrix.cuh.
template<typename T> size_type math::device_matrix< T >::size () const inline noexcept
Definition at line 169 of file device_matrix.cuh.
Referenced by math::device_matrix< T >::almostEqual(), math::device_matrix< T >::Identity(), math::device_matrix< T >::operator+(), math::device_matrix< T >::operator-(), and math::device_matrix< T >::operator==().
template<typename T> void math::device_matrix< T >::swap (device_matrix< T > & other) inline noexcept
Definition at line 159 of file device_matrix.cuh.
The documentation for this class was generated from the following file:
/home/travis/build/hmenke/cpp-patterns/device_matrix/device_matrix.cuh