CPP Patterns: device_matrix< T, Policy > Class Template Reference
device_matrix< T, Policy > Class Template Reference
#include <device_matrix.hpp>
Public Types
using storage_type = typename Policy::template vector< T >
using value_type = typename storage_type::value_type
using size_type = typename storage_type::size_type
using difference_type = typename storage_type::difference_type
using reference = typename storage_type::reference
using const_reference = typename storage_type::const_reference
using pointer = typename storage_type::pointer
using const_pointer = typename storage_type::const_pointer
using iterator = typename storage_type::iterator
Public Member Functions
device_matrix (size_type rows, size_type cols)
reference operator() (size_type row, size_type col) noexcept
const_reference operator() (size_type row, size_type col) const noexcept
void fill (value_type const &value) noexcept(std::is_nothrow_copy_assignable< value_type >::value)
void swap (device_matrix &other) noexcept(noexcept(m_data.swap(other.m_data)))
pointer data () noexcept
const_pointer data () const noexcept
size_type rows () const noexcept
size_type cols () const noexcept
size_type size () const noexcept
device_matrix operator* (device_matrix const &B) const
Matrix-matrix multiplication.
storage_type operator* (storage_type const &x) const
Matrix-vector multiplication.
device_matrix operator+ (device_matrix const &B) const
Add element-wise.
device_matrix operator- (device_matrix const &B) const
Subtract element-wise.
device_matrix & operator- ()
Negate element-wise.
bool operator== (device_matrix const &B) const
Compare for exact bit-wise equality.
bool almostEqual (device_matrix const &B, value_type const epsilon=std::numeric_limits< value_type >::epsilon()) const
device_matrix transpose () const
Compute the transpose.
device_matrix inverse () const
Compute the inverse.
Static Public Member Functions
static device_matrix Identity (size_type rows, size_type cols)
Generate an identity matrix with size rows x cols.
Detailed Description
template<typename T, typename Policy = policy::host>
class device_matrix< T, Policy >
Definition at line 233 of file device_matrix.hpp.
Member Typedef Documentation
const_pointer
template<typename T , typename Policy = policy::host> using device_matrix< T, Policy >::const_pointer = typename storage_type::const_pointer
Definition at line 242 of file device_matrix.hpp.
const_reference
template<typename T , typename Policy = policy::host> using device_matrix< T, Policy >::const_reference = typename storage_type::const_reference
Definition at line 240 of file device_matrix.hpp.
difference_type
template<typename T , typename Policy = policy::host> using device_matrix< T, Policy >::difference_type = typename storage_type::difference_type
Definition at line 238 of file device_matrix.hpp.
iterator
template<typename T , typename Policy = policy::host> using device_matrix< T, Policy >::iterator = typename storage_type::iterator
Definition at line 243 of file device_matrix.hpp.
pointer
template<typename T , typename Policy = policy::host> using device_matrix< T, Policy >::pointer = typename storage_type::pointer
Definition at line 241 of file device_matrix.hpp.
reference
template<typename T , typename Policy = policy::host> using device_matrix< T, Policy >::reference = typename storage_type::reference
Definition at line 239 of file device_matrix.hpp.
size_type
template<typename T , typename Policy = policy::host> using device_matrix< T, Policy >::size_type = typename storage_type::size_type
Definition at line 237 of file device_matrix.hpp.
storage_type
template<typename T , typename Policy = policy::host> using device_matrix< T, Policy >::storage_type = typename Policy::template vector<T>
Definition at line 235 of file device_matrix.hpp.
value_type
template<typename T , typename Policy = policy::host> using device_matrix< T, Policy >::value_type = typename storage_type::value_type
Definition at line 236 of file device_matrix.hpp.
Constructor & Destructor Documentation
device_matrix()
template<typename T , typename Policy = policy::host> device_matrix< T, Policy >::device_matrix (size_type rows, size_type cols) inline explicit
Definition at line 252 of file device_matrix.hpp.
Member Function Documentation
cols()
template<typename T , typename Policy = policy::host> size_type device_matrix< T, Policy >::cols () const inline noexcept
Definition at line 278 of file device_matrix.hpp.
Referenced by device_matrix< T, Policy >::Identity(), and operator<<().
data() [1/2]
template<typename T , typename Policy = policy::host> const_pointer device_matrix< T, Policy >::data () const inline noexcept
Definition at line 276 of file device_matrix.hpp.
data() [2/2]
template<typename T , typename Policy = policy::host> pointer device_matrix< T, Policy >::data () inline noexcept
Definition at line 275 of file device_matrix.hpp.
Referenced by device_matrix< T, Policy >::almostEqual(), device_matrix< T, Policy >::Identity(), device_matrix< T, Policy >::operator*(), device_matrix< T, Policy >::operator+(), device_matrix< T, Policy >::operator-(), device_matrix< T, Policy >::operator==(), and device_matrix< T, Policy >::transpose().
fill()
template<typename T , typename Policy = policy::host> void device_matrix< T, Policy >::fill (value_type const & value) inline noexcept
Definition at line 263 of file device_matrix.hpp.
operator()() [1/2]
template<typename T , typename Policy = policy::host> const_reference device_matrix< T, Policy >::operator() (size_type row, size_type col) const inline noexcept
Definition at line 259 of file device_matrix.hpp.
operator()() [2/2]
template<typename T , typename Policy = policy::host> reference device_matrix< T, Policy >::operator() (size_type row, size_type col) inline noexcept
Definition at line 255 of file device_matrix.hpp.
rows()
template<typename T , typename Policy = policy::host> size_type device_matrix< T, Policy >::rows () const inline noexcept
Definition at line 277 of file device_matrix.hpp.
Referenced by device_matrix< T, Policy >::Identity(), and operator<<().
size()
template<typename T , typename Policy = policy::host> size_type device_matrix< T, Policy >::size () const inline noexcept
Definition at line 279 of file device_matrix.hpp.
Referenced by device_matrix< T, Policy >::almostEqual(), device_matrix< T, Policy >::Identity(), device_matrix< T, Policy >::operator+(), device_matrix< T, Policy >::operator-(), device_matrix< T, Policy >::operator==(), test_cpu(), and test_gpu().
swap()
template<typename T , typename Policy = policy::host> void device_matrix< T, Policy >::swap (device_matrix< T, Policy > & other) inline noexcept
Definition at line 269 of file device_matrix.hpp.
The documentation for this class was generated from the following file:
/home/runner/work/cpp-patterns/cpp-patterns/device_matrix/device_matrix.hpp