CPP Patterns: multi_array< T, N > Class Template Reference
multi_array< T, N > Class Template Reference
#include <multi_array.hpp>
Public Types
using value_type = T
using size_type = std::size_t
using difference_type = std::ptrdiff_t
using reference = value_type &
using const_reference = const value_type &
using pointer = value_type *
using const_pointer = const value_type *
using iterator = pointer
Public Member Functions
constexpr DEVICE_FUNC multi_array ()
template<typename... U>
constexpr DEVICE_FUNC multi_array (U... data)
Constructor for aggregate initializers.
DEVICE_FUNC void fill (value_type const &value) noexcept(std::is_nothrow_copy_assignable< value_type >::value)
fill the container with specified value
DEVICE_FUNC void swap (multi_array &other) noexcept(std::is_nothrow_move_assignable< value_type >::value)
swaps the contents
constexpr DEVICE_FUNC iterator begin () const noexcept
returns an iterator to the beginning
constexpr DEVICE_FUNC iterator end () const noexcept
returns an iterator to the end
DEVICE_FUNC CXX14_CONSTEXPR pointer data () noexcept
direct access to the underlying array
DEVICE_FUNC CXX14_CONSTEXPR const_pointer data () const noexcept
template<typename... Idx>
DEVICE_FUNC CXX14_CONSTEXPR reference operator() (Idx... idx)
template<typename... Idx>
constexpr DEVICE_FUNC const_reference operator() (Idx... idx) const
template<size_type i>
constexpr DEVICE_FUNC size_type size () const noexcept
constexpr DEVICE_FUNC size_type size () const noexcept
returns the number of elements
Detailed Description
template<typename T, std::size_t... N>
class multi_array< T, N >
Multidimensional array similar to std::array
Storage is always in row-major order for easy list initialization
Template Parameters
T value type
N list of dimensions
Definition at line 116 of file multi_array.hpp.
Member Typedef Documentation
const_pointer
template<typename T , std::size_t... N> using multi_array< T, N >::const_pointer = const value_type *
Definition at line 124 of file multi_array.hpp.
const_reference
template<typename T , std::size_t... N> using multi_array< T, N >::const_reference = const value_type &
Definition at line 122 of file multi_array.hpp.
difference_type
template<typename T , std::size_t... N> using multi_array< T, N >::difference_type = std::ptrdiff_t
Definition at line 120 of file multi_array.hpp.
iterator
template<typename T , std::size_t... N> using multi_array< T, N >::iterator = pointer
Definition at line 125 of file multi_array.hpp.
pointer
template<typename T , std::size_t... N> using multi_array< T, N >::pointer = value_type *
Definition at line 123 of file multi_array.hpp.
reference
template<typename T , std::size_t... N> using multi_array< T, N >::reference = value_type &
Definition at line 121 of file multi_array.hpp.
size_type
template<typename T , std::size_t... N> using multi_array< T, N >::size_type = std::size_t
Definition at line 119 of file multi_array.hpp.
value_type
template<typename T , std::size_t... N> using multi_array< T, N >::value_type = T
Definition at line 118 of file multi_array.hpp.
Constructor & Destructor Documentation
multi_array() [1/2]
template<typename T , std::size_t... N> constexpr DEVICE_FUNC multi_array< T, N >::multi_array () inline constexpr
Definition at line 135 of file multi_array.hpp.
multi_array() [2/2]
template<typename T , std::size_t... N> template<typename... U> constexpr DEVICE_FUNC multi_array< T, N >::multi_array (U... data) inline constexpr
Constructor for aggregate initializers.
Definition at line 139 of file multi_array.hpp.
References multi_array< T, N >::data().
Member Function Documentation
begin()
template<typename T , std::size_t... N> constexpr DEVICE_FUNC iterator multi_array< T, N >::begin () const inline constexpr noexcept
returns an iterator to the beginning
Definition at line 162 of file multi_array.hpp.
References multi_array< T, N >::data().
Referenced by multi_array< T, N >::fill(), and multi_array< T, N >::swap().
data() [1/2]
template<typename T , std::size_t... N> DEVICE_FUNC CXX14_CONSTEXPR const_pointer multi_array< T, N >::data () const inline noexcept
Definition at line 174 of file multi_array.hpp.
data() [2/2]
template<typename T , std::size_t... N> DEVICE_FUNC CXX14_CONSTEXPR pointer multi_array< T, N >::data () inline noexcept
direct access to the underlying array
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 172 of file multi_array.hpp.
Referenced by multi_array< T, N >::begin(), multi_array< T, N >::end(), and multi_array< T, N >::multi_array().
end()
template<typename T , std::size_t... N> constexpr DEVICE_FUNC iterator multi_array< T, N >::end () const inline constexpr noexcept
returns an iterator to the end
Definition at line 167 of file multi_array.hpp.
References multi_array< T, N >::data().
Referenced by multi_array< T, N >::fill(), and multi_array< T, N >::swap().
fill()
template<typename T , std::size_t... N> DEVICE_FUNC void multi_array< T, N >::fill (value_type const & value) inline noexcept
fill the container with specified value
Definition at line 143 of file multi_array.hpp.
References multi_array< T, N >::begin(), and multi_array< T, N >::end().
operator()() [1/2]
template<typename T , std::size_t... N> template<typename... Idx> DEVICE_FUNC CXX14_CONSTEXPR reference multi_array< T, N >::operator() (Idx... idx) inline
access specified element
Exceptions
std::out_of_range if index is out of range (only in DEBUG mode)
Definition at line 182 of file multi_array.hpp.
operator()() [2/2]
template<typename T , std::size_t... N> template<typename... Idx> constexpr DEVICE_FUNC const_reference multi_array< T, N >::operator() (Idx... idx) const inline constexpr
Definition at line 200 of file multi_array.hpp.
size() [1/2]
template<typename T , std::size_t... N> template<size_type i> constexpr DEVICE_FUNC size_type multi_array< T, N >::size () const inline constexpr noexcept
returns the size along dimension i
Template Parameters
i dimension
Definition at line 220 of file multi_array.hpp.
Referenced by main().
size() [2/2]
template<typename T , std::size_t... N> constexpr DEVICE_FUNC size_type multi_array< T, N >::size () const inline constexpr noexcept
returns the number of elements
Definition at line 227 of file multi_array.hpp.
swap()
template<typename T , std::size_t... N> DEVICE_FUNC void multi_array< T, N >::swap (multi_array< T, N > & other) inline noexcept
swaps the contents
Definition at line 151 of file multi_array.hpp.
References multi_array< T, N >::begin(), and multi_array< T, N >::end().
The documentation for this class was generated from the following file:
/home/runner/work/cpp-patterns/cpp-patterns/multi_array/multi_array.hpp