CPP Patterns: /home/runner/work/cpp-patterns/cpp-patterns/device_matrix/device_matrix.hpp File Reference
device_matrix.hpp File Reference
#include <iomanip>
#include <limits>
#include <type_traits>
#include <thrust/device_vector.h>
#include <thrust/execution_policy.h>
#include <thrust/functional.h>
#include <thrust/tabulate.h>
#include <cublas_v2.h>
#include <cusolverDn.h>
Data Structures
struct policy::host
struct policy::device
class device_matrix< T, Policy >
class device_matrix_view< T, Policy >
class device_vector_view< T, Policy >
Namespaces
policy
Macros
#define DEVICE_FUNC
Functions
DEVICE_FUNC thrust::tuple< size_t, size_t > unravel_index (size_t index, size_t lda)
template<typename T >
thrust::device_vector< T > operator+ (thrust::device_vector< T > const &x, thrust::device_vector< T > const &y)
Vector addition.
template<typename T >
thrust::host_vector< T > operator+ (thrust::host_vector< T > const &x, thrust::host_vector< T > const &y)
template<typename T >
std::ostream & operator<< (std::ostream &os, thrust::device_vector< T > const &v)
template<typename T >
std::ostream & operator<< (std::ostream &os, thrust::host_vector< T > const &v)
template<typename T , typename Policy >
std::ostream & operator<< (std::ostream &os, device_matrix< T, Policy > const &m)
Macro Definition Documentation
DEVICE_FUNC
#define DEVICE_FUNC
Definition at line 18 of file device_matrix.hpp.
Function Documentation
operator+() [1/2]
template<typename T > thrust::device_vector<T> operator+ (thrust::device_vector< T > const & x, thrust::device_vector< T > const & y)
Vector addition.
Definition at line 479 of file device_matrix.hpp.
operator+() [2/2]
template<typename T > thrust::host_vector<T> operator+ (thrust::host_vector< T > const & x, thrust::host_vector< T > const & y)
Definition at line 489 of file device_matrix.hpp.
operator<<() [1/3]
template<typename T , typename Policy > std::ostream& operator<< (std::ostream & os, device_matrix< T, Policy > const & m)
Definition at line 525 of file device_matrix.hpp.
References device_matrix< T, Policy >::cols(), and device_matrix< T, Policy >::rows().
operator<<() [2/3]
template<typename T > std::ostream& operator<< (std::ostream & os, thrust::device_vector< T > const & v)
Definition at line 499 of file device_matrix.hpp.
operator<<() [3/3]
template<typename T > std::ostream& operator<< (std::ostream & os, thrust::host_vector< T > const & v)
Definition at line 512 of file device_matrix.hpp.
unravel_index()
DEVICE_FUNC thrust::tuple<size_t, size_t> unravel_index (size_t index, size_t lda) inline
Definition at line 37 of file device_matrix.hpp.
Referenced by cpu_count_elements::operator()(), and gpu_count_elements::operator()().