CPP Patterns: Comparison
Comparison
Functions
bool device_matrix< T, Policy >::operator== (device_matrix const &B) const
Compare for exact bit-wise equality.
bool device_matrix< T, Policy >::almostEqual (device_matrix const &B, value_type const epsilon=std::numeric_limits< value_type >::epsilon()) const
Detailed Description
Function Documentation
template<typename T, typename Policy = policy::host> bool device_matrix< T, Policy >::almostEqual (device_matrix< T, Policy > const & B, value_type const epsilon = std::numeric_limits<value_type>::epsilon()) const inline
Compare for equality with threshold epsilon.
Parameters
epsilon maximum allowed difference
Definition at line 347 of file device_matrix.hpp.
References device_matrix< T, Policy >::data(), and device_matrix< T, Policy >::size().
Referenced by test_cpu(), and test_gpu().
template<typename T, typename Policy = policy::host> bool device_matrix< T, Policy >::operator== (device_matrix< T, Policy > const & B) const inline
Compare for exact bit-wise equality.
Definition at line 339 of file device_matrix.hpp.
References device_matrix< T, Policy >::data(), and device_matrix< T, Policy >::size().