CPP Patterns: Arithmetic operators
Arithmetic operators
Functions
device_matrix device_matrix< T, Policy >::operator* (device_matrix const &B) const
Matrix-matrix multiplication.
storage_type device_matrix< T, Policy >::operator* (storage_type const &x) const
Matrix-vector multiplication.
device_matrix device_matrix< T, Policy >::operator+ (device_matrix const &B) const
Add element-wise.
device_matrix device_matrix< T, Policy >::operator- (device_matrix const &B) const
Subtract element-wise.
device_matrix & device_matrix< T, Policy >::operator- ()
Negate element-wise.
Detailed Description
Function Documentation
operator*() [1/2]
template<typename T , typename Policy = policy::host> device_matrix device_matrix< T, Policy >::operator* (device_matrix< T, Policy > const & B) const inline
Matrix-matrix multiplication.
Definition at line 285 of file device_matrix.hpp.
References device_matrix< T, Policy >::data().
operator*() [2/2]
template<typename T , typename Policy = policy::host> storage_type device_matrix< T, Policy >::operator* (storage_type const & x) const inline
Matrix-vector multiplication.
Definition at line 296 of file device_matrix.hpp.
References device_matrix< T, Policy >::data().
operator+()
template<typename T , typename Policy = policy::host> device_matrix device_matrix< T, Policy >::operator+ (device_matrix< T, Policy > const & B) const inline
Add element-wise.
Definition at line 307 of file device_matrix.hpp.
References device_matrix< T, Policy >::data(), and device_matrix< T, Policy >::size().
operator-() [1/2]
template<typename T , typename Policy = policy::host> device_matrix& device_matrix< T, Policy >::operator- () inline
Negate element-wise.
Definition at line 327 of file device_matrix.hpp.
References device_matrix< T, Policy >::data(), and device_matrix< T, Policy >::size().
operator-() [2/2]
template<typename T , typename Policy = policy::host> device_matrix device_matrix< T, Policy >::operator- (device_matrix< T, Policy > const & B) const inline
Subtract element-wise.
Definition at line 317 of file device_matrix.hpp.
References device_matrix< T, Policy >::data(), and device_matrix< T, Policy >::size().