CPP Patterns: /home/travis/build/hmenke/cpp-patterns/integer_sequence/test.cpp File Reference
test.cpp File Reference
#include <iostream>
#include <string>
#include <tuple>
#include <vector>
Data Structures
struct integer_sequence< T, Is >
struct make_integer_sequence_impl< T, N, Is >
struct make_integer_sequence_impl< T, std::integral_constant< T, 0 >, Is...>
struct make_integer_sequence_t< T, N >
struct make_integer_sequence_t< T, std::integral_constant< T, 0 > >
struct make_integer_sequence_t< T, std::integral_constant< T, 1 > >
struct Bytes
struct Visitor
Typedefs
template<typename T , T N>
using make_integer_sequence = typename make_integer_sequence_t< T, std::integral_constant< T, N >>::type
template<size_t... Is>
using index_sequence = integer_sequence< size_t, Is...>
template<size_t N>
using make_index_sequence = make_integer_sequence< size_t, N >
Functions
template<typename T , typename F , size_t... Is>
void for_each_impl (T &&t, F &&f, index_sequence< Is...>)
template<typename... Args, typename F >
void for_each (std::tuple< Args...> const &t, F &&f)
int main ()
Typedef Documentation
template<size_t... Is> using index_sequence = integer_sequence<size_t,Is...>
Definition at line 61 of file test.cpp.
template<size_t N> using make_index_sequence = make_integer_sequence<size_t,N>
Definition at line 64 of file test.cpp.
template<typename T , T N> using make_integer_sequence = typename make_integer_sequence_t<T,std::integral_constant<T,N>>::type
Definition at line 56 of file test.cpp.
Function Documentation
template<typename... Args, typename F > void for_each (std::tuple< Args...> const & t, F && f)
Definition at line 77 of file test.cpp.
References f(), and for_each_impl().
Referenced by main(), test_cpu(), and test_gpu().
template<typename T , typename F , size_t... Is> void for_each_impl (T && t, F && f, index_sequence< Is...>)
Definition at line 70 of file test.cpp.
References f().
Referenced by for_each().
int main (void)
Definition at line 102 of file test.cpp.
References for_each().