CPP Patterns: /home/runner/work/cpp-patterns/cpp-patterns/device_matrix/runner.cpp File Reference
runner.cpp File Reference
Functions
void test_cpu ()
void test_gpu ()
int main ()
Function Documentation
main()
int main ()
Definition at line 4 of file runner.cpp.
References test_cpu(), and test_gpu().
test_cpu()
void test_cpu ()
Definition at line 13 of file test.cpp.
References device_matrix< T, Policy >::almostEqual(), for_each(), device_matrix< T, Policy >::Identity(), device_matrix< T, Policy >::inverse(), device_matrix< T, Policy >::size(), and device_matrix< T, Policy >::transpose().
Referenced by main().
test_gpu()
void test_gpu ()
Definition at line 13 of file test.cu.
References device_matrix< T, Policy >::almostEqual(), for_each(), device_matrix< T, Policy >::Identity(), device_matrix< T, Policy >::inverse(), device_matrix< T, Policy >::size(), and device_matrix< T, Policy >::transpose().
Referenced by main().