CPP Patterns: /home/runner/work/cpp-patterns/cpp-patterns/device_matrix/test.cu File Reference
test.cu File Reference
#include <iostream>
#include "device_matrix.hpp"
Data Structures
struct gpu_count_elements
Functions
void test_gpu ()
Function Documentation
test_gpu()
void test_gpu ()
Definition at line 13 of file test.cu.
References device_matrix< T, Policy >::almostEqual(), for_each(), device_matrix< T, Policy >::Identity(), device_matrix< T, Policy >::inverse(), device_matrix< T, Policy >::size(), and device_matrix< T, Policy >::transpose().
Referenced by main().