CPP Patterns: /home/runner/work/cpp-patterns/cpp-patterns/unroll/unroll.hpp File Reference
unroll.hpp File Reference
#include <type_traits>
#include <utility>
Data Structures
struct range< Lower, Upper >
Compile-time loop bounds.
Macros
#define FORCE_INLINE inline
Typedefs
using ssize_t = std::make_signed< std::size_t >::type
Signed version of std::size_t.
Functions
template<typename Range , typename F >
constexpr FORCE_INLINE int unroll (F &&f)
Unroll loop at compile-time.
template<typename Range0 , typename Range1 , typename... Range, typename F >
constexpr FORCE_INLINE int unroll (F &&f)
Unroll loop at compile-time (nested case)
Macro Definition Documentation
FORCE_INLINE
#define FORCE_INLINE inline
Definition at line 16 of file unroll.hpp.
Typedef Documentation
ssize_t
using ssize_t = std::make_signed<std::size_t>::type
Signed version of std::size_t.
Definition at line 9 of file unroll.hpp.
Function Documentation
unroll() [1/2]
template<typename Range , typename F > constexpr FORCE_INLINE int unroll (F && f) constexpr
Unroll loop at compile-time.
Definition at line 89 of file unroll.hpp.
References f().
Referenced by main().
unroll() [2/2]
template<typename Range0 , typename Range1 , typename... Range, typename F > constexpr FORCE_INLINE int unroll (F && f) constexpr
Unroll loop at compile-time (nested case)
Definition at line 97 of file unroll.hpp.
References f().