name: Linux

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -qq \
            doxygen \
            libboost-dev \
            libboost-serialization-dev \
            libzmq3-dev \
            python3-dev \
            python3-zmq \
            swig \

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release
          cmake --build . --target doxygen --config Release
          cd -

      - name: Deploy pages
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: build/doc/html
