name: Windows

on: push

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            C:\vcpkg\installed
            C:\vcpkg\packages
          key: ${{ runner.os }}-dependencies

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: vcpkg.exe install boost-format boost-iostreams boost-serialization boost-variant zeromq --triplet x64-windows

      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call %CONDA%\Scripts\activate.bat
          md build
          cd build
          cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DCMAKE_TOOLCHAIN_FILE="%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake" ..
          cmake --build . --config Release
